-- =============================================================================
-- ADD key_suppliers + company_briefing to company_contexts
-- =============================================================================
-- Migration: 212_company_suppliers_briefing.sql
-- Description: Add structured suppliers + narrative briefing for insider context
-- Created: 2026-02-17
-- =============================================================================

-- Structured supplier data [{ name, notes }]
ALTER TABLE company_contexts
  ADD COLUMN IF NOT EXISTS key_suppliers JSONB DEFAULT '[]'::jsonb;

-- Pre-generated narrative briefing (insider onboarding memo)
-- Generated by LLM on form save, injected into every chat request
ALTER TABLE company_contexts
  ADD COLUMN IF NOT EXISTS company_briefing TEXT;
